### ISSUE TITLE
press Refresh in "TEMPLATES" error in console

### ISSUE THREAD

**Issue by pvp-by** [Nuked88/ComfyUI-N-Sidebar#80]
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/10133995/344d449f-e663-4b5f-a853-0c7d1bb7988f)
I have 2 user nickname, 0 user name "default"
Only section "TEMPLATES"
If refresh page comfyUI , error doubled.
Console:
```
Error handling request
Traceback (most recent call last):
  File "D:\comfy\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfy\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfy\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfy\ComfyUI\server.py", line 42, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfy\ComfyUI\server.py", line 54, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfy\ComfyUI\app\user_manager.py", line 153, in getuserdata
    path = get_user_data_path(request, check_exists=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfy\ComfyUI\app\user_manager.py", line 142, in get_user_data_path
    path = self.get_request_user_filepath(request, file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfy\ComfyUI\app\user_manager.py", line 54, in get_request_user_filepath
    user = self.get_request_user_id(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfy\ComfyUI\app\user_manager.py", line 42, in get_request_user_id
    raise KeyError("Unknown user: " + user)
KeyError: 'Unknown user: default'
```
Console js in chrome:
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/10133995/bd730aca-376b-4baa-a0df-daa3469ef3f9)

**Comment by Nuked88** [comment]
I added support for multi-user in templates!
